### ISSUE TITLE
Discuss a possible implementation upgrade to better match tradingview's pinescript way of code

### ISSUE THREAD

**Issue by saniales** [markcheno/go-talib#10]
This would allow to easily import pinescript strategies into go talib based programs

as far as I've seen, the more problematic feature is the [`security`](https://www.tradingview.com/wiki/Context_Switching,_The_%E2%80%98security%E2%80%99_Function)  function by tradingview, which allows to switch context and have new candles and manipulate them

from function signature (https://it.tradingview.com/study-script-reference/#fun_security) in its simplest form:
``` javascript
security(symbol, resolution, expression)
```
where 
 - *symbol* is used to get the candles from the tradingview chart (so it can be substituted with the input of high/low/open/close four []float64 values we can get from any exchange or broker api.
 - *resolution* is usually a timeframe related, so it can be merged with the 4 float64 arrays as symbol
 - *expression* is the manipulation we need to perform on data

an example of call would be 
``` javascript
security("BTCUSD", "1d", close) // gets the close values from btcusd 1 day chart
security(heikinashi("BTCUSD"), "30m", hlc3) // gets the heikinashi candles of btcusd 30m chart, then performs HLC3 [(high+low+close) / 3] to the gotten series and returns it
```

To translate this in go-talib way I have an idea:
let's create the following function
``` go
func security(inHigh, inOpen, inClose, inLow []float64, expression Manipulator) []float64
```

the in-arrays represent the symbol + resolution parameters results while the manipulator function will defined as follow:
``` go
type Manipulator func(inHigh, inOpen, inClose, inLow []float64) []float64
```
In this way we would be able to use it like this:
``` go
// we do not really care about how candles are extracted, let's assume to use the following function
inHigh, inOpen, inClose, inLow := extractFromSomeCandles(symbol, resolution) // we can extract it from cryptocurrency exchanges as well as from forex brokers
manipulator := talib.Hlc3 // we need to change the signature of the function to follow manipulator signature
// then we use it
result := talib.Security(inHigh, inOpen, inClose, inLow, manipulator)
```

We can also wrap manipulators one inside another, like the following:
``` go
manipulator1 := talib.Hlc3
manipulator2 := func(inHigh, inOpen, inClose, inLow []float64) []float64 {
    manipulatedHigh, manipulatedOpen, manipulatedClose, manipulatedLow := manipulateInSomeWay(inHigh, inOpen, inClose, inLow)
    // pass manipulated array to the second function
    return manipulator1(manipulatedHigh, manipulatedOpen, manipulatedClose, manipulatedLow)
}
```

A better way should be found though, maybe through the use of a `Wrap` function in some way

Another idea would be to create a ContextSwitcher function which is like the following
``` go
func(inHigh, inOpen, inClose, inLow []float64) ([]float64, []float64, []float64, []float64)
```

@markcheno what do you think? is it possible in your opinion. In case it's not I can create a separate repo, detaching from talib

**Comment by saniales** [comment]
Pinescript general reference : https://it.tradingview.com/study-script-reference

**Comment by markcheno** [comment]
Are you proposing to re-create Pinescript in Go? If so, I think a new repository would be best.

**Comment by saniales** [comment]
What I was thinking was to fuse existing talib-implementation into pinescript way of code, not to directly translate pinescript itself, since pinescript has talib features built into it

**Comment by saniales** [comment]
@markcheno let's use an example from the library
``` go
inHigh, inOpen, inClose, inLow := extractFromSomeCandles(symbol, resolution) // we can extract it from cryptocurrency exchanges as well as from forex brokers
results := talib.Security(inHigh, inOpen, inClose, inLow, talib.AvgPrice)
```

**Comment by markcheno** [comment]
If you want to re-create all the functions with a different signature, I think it would be best to start a new repository.
