### ISSUE TITLE
HtTrendline Gives  index out of range

### ISSUE THREAD

**Issue by VarunBatraIT** [markcheno/go-talib#2]
panic: runtime error: index out of range
goroutine 7 [running]:
github.com/markcheno/go-talib.HtTrendline(0xc42025ea00, 0x1a, 0x20, 0x6, 0xc8, 0xc420268274)
	/home/codevarun/go/src/github.com/markcheno/go-talib/talib.go:185 +0x10b5

**Comment by markcheno** [comment]
I can't tell if there is a problem with the info given. My guess would be bad input data.

**Comment by VarunBatraIT** [comment]
Hi, Same data worked on a wrapper. (github.com/d4l3k/talib)

**Comment by markcheno** [comment]
If you can give me example data to reproduce the problem, I can fix it.

**Comment by pharrisee** [comment]
Hilbert Trendline is based on a minimum of 63 points of data it seems, which is backed up by the comment on line 142 of talib.go
