### ISSUE TITLE
RSI indicator not accurite if candles not so enough 

### ISSUE THREAD

**Issue by gpmn** [markcheno/go-talib#20]
e.g. 
if it is feed with 11 candles to calculate rsi for 10 days, the result deviation is very heavily ;
if it is feed with 20 candles to calculate rsi for 10 days, the result deviation is small.
if it is feed with 30 candles, the result is nearly same with other libraries.

**Comment by markcheno** [comment]
All of the indicators have a variable warm up period before they stabilize. This code is a direct port of ta-lib, so it should act the same. No guarantees for other libraries.
