### ISSUE TITLE
Query on plus_di (and similar functions)

### ISSUE THREAD

**Issue by icecolbeveridge** [markcheno/go-talib#22]
https://github.com/markcheno/go-talib/blob/cd53a9264d70bedcff891f59bf153275f524c100/talib.go#L2500

Hello,

I wanted to check the maths on the DI implementation -- I think there might be an off-by-one error in how it's set up. I would expect the first values of  `prevTR` and `prevPlusDM` to be the sum of the first (period) readings rather than the first (period - 1) -- otherwise these values are systematically under-weighted and (I believe) the ratio converges to the correct value more slowly.

It's more than possible that I've made an error or misunderstood, but thought I ought to flag it up.

Many thanks.

**Comment by markcheno** [comment]
There very well may be a bug, but I test the output against the official TaLib and it matches. Therefore I am hesitant to make any changes. Thanks for the heads up.

**Comment by icecolbeveridge** [comment]
Understood, thanks Mark.
