### ISSUE TITLE
Index out of range with Stoch()

### ISSUE THREAD

**Issue by btjsteens** [markcheno/go-talib#3]
**Steps to reproduce**
In your talib_test.go file, change inFastKPeriod to a higher value, e.g. 12.

	slowk, slowd := Stoch(testHigh, testLow, testClose, 12, 3, SMA, 3, SMA)

Index out of range error occurs on the following line:
		outSlowK[j] = tempBuffer1[i]

**Comment by greatGregLiu** [comment]
exactly same problem here. Please fix it. Thanks

**Comment by markcheno** [comment]
This should be fixed with the latest commit. Thanks for the heads up.
